// claims.js — 12 representative mock claims spanning sources and edge cases.
// Source-agnostic shape per align Claim Adapter Contract:
//   id, text, source, time (opt), icon (opt), desc (opt), detail (opt),
//   categories (opt), files (opt), verifiable (opt — false = machine-only)

window.MOCK_CLAIMS = [
  {
    id: 1,
    time: "08:30",
    icon: "calendar",
    source: "Calendar · Mon May 20",
    text: "Standup moved from 9:00 to 10:00 Wednesday to accommodate David's flight.",
    desc: "Rescheduled by Priya, two attendees not yet confirmed.",
    detail: "Original: Mon-Fri 09:00–09:15 (recurring).\nProposed: Mon, Tue, Thu, Fri 09:00; Wed 10:00–10:15 (one-off override).\nDeclined responses: 0.\nTentative: 2 (David, Marcus).",
    categories: ["scheduling", "team"],
    files: ["calendar.ics"],
  },
  {
    id: 2,
    time: "08:32",
    icon: "gmail",
    source: "Gmail · sarah@oakridge.io",
    text: "Sarah confirmed Q3 budget approval for the platform initiative — $480k cleared.",
    desc: "Reply to your Friday thread, marked as final.",
    detail: "Subject: RE: Q3 platform budget — final ask\n\n> The board signed off this morning. $480k cleared, no further questions. Send the kickoff calendar invite by EOW please.\n\nThread participants: 4 (Sarah, Priya, Marcus, you).",
    categories: ["budget", "platform"],
  },
  {
    id: 3,
    time: "09:14",
    icon: "slack",
    source: "Slack · #eng-deploy",
    text: "All production deploys paused until security review of the auth refactor lands.",
    desc: "Pinned by @marcus, 6 ✅ reactions.",
    detail: "Pinned message from marcus 09:11:\n\n> Pausing deploys to prod until Aiden's security review of the auth refactor lands. Hotfixes are fine if you ping me. ETA Wed EOD.\n\nReactions: ✅ 6  👀 2  🙏 1",
    categories: ["deploy", "security"],
  },
  {
    id: 4,
    time: "10:02",
    icon: "fireflies",
    source: "Fireflies · Eng sync",
    text: "David committed to shipping the OAuth refactor by Friday EOD.",
    desc: "Spoken commitment, 32:14 into the call.",
    detail: "Transcript excerpt 32:14–32:48:\n\nDavid: \"…yeah I'll have the refactor in review by Friday EOD, worst case Monday morning. I'm pairing with Aiden on the session bit Wednesday.\"\n\nPriya: \"Friday works. I'll let the customer team know.\"",
    categories: ["commitment", "auth"],
    link: "https://fireflies.example/m/eng-sync-2026-05-20",
  },
  {
    id: 5,
    time: "11:40",
    icon: "drive",
    source: "Drive · Q3 OKR draft",
    text: "Q3 OKR doc was last edited by Priya on May 18 — three open comments unresolved.",
    desc: "Document state, not a spoken commitment.",
    detail: "File: q3-okr-draft.gdoc\nLast modified: 2026-05-18 16:42 by priya@oakridge.io\nOpen comments: 3 (all on the 'Platform reliability' section).\nResolved comments since May 1: 11.",
    categories: ["okr", "planning"],
    verifiable: false,
  },
  {
    id: 6,
    time: "12:15",
    icon: "calendar",
    source: "Calendar · 1:1 series",
    text: "Your 1:1 with Marcus rescheduled to next Tuesday 14:00.",
    desc: "Moved by Marcus, no reason given.",
    categories: ["scheduling", "1:1"],
  },
  {
    id: 7,
    time: "13:05",
    icon: "gmail",
    source: "Gmail · billing@meridian.co",
    text: "Customer Meridian signed the renewal — 24-month term, +18% expansion.",
    desc: "Signed contract attached, countersigned by their CFO.",
    detail: "Term: 2026-06-01 → 2028-05-31\nValue: $312k/yr (+18% over current)\nSigned by: Elena Vasquez, CFO, Meridian Co\nCountersigned: 2026-05-23 17:22 UTC",
    categories: ["customer", "renewal"],
    files: ["meridian-renewal-2026.pdf"],
  },
  {
    id: 8,
    time: "14:30",
    icon: "slack",
    source: "Slack · #design-system",
    text: "Design system v2 shipped to production at 14:12 — zero rollback signals so far.",
    desc: "Auto-posted by the deploy bot.",
    detail: "deploy-bot 14:12:\n> design-system@2.0.0 → production ✅\n> Build: 4892\n> Rollback hash: 8a2f1b9\n> Health: green across all monitored surfaces (45m window)",
    categories: ["launch", "design-system"],
  },
  {
    id: 9,
    time: "15:00",
    icon: "fireflies",
    source: "Fireflies · Marketing sync",
    text: "Marketing is pushing for the public launch to slip from June 3 to June 10.",
    desc: "Raised by Lena, not yet decided.",
    detail: "Transcript excerpt 18:02–19:30:\n\nLena: \"PR window is tight on June 3 — there are two competitor launches that week. June 10 gives us clean air and lines up with the conference keynote.\"\n\nNo decision recorded. Action: revisit with David Thursday.",
    categories: ["launch", "marketing"],
  },
  {
    id: 10,
    icon: "fabric",
    source: "Smart-memory · pattern",
    text: "You consistently prefer async written standups over synchronous video standups.",
    desc: "Inferred from 7 prior corrections; pattern confidence 0.82.",
    detail: "Evidence pool:\n  · 2026-04-12 align-rhythm: rated 'almost' on standup time-slot claim, noted 'we don't do video'\n  · 2026-04-19 align-rhythm: rated 'wrong' on attendance claim, noted 'async only'\n  · 2026-05-03 align-todo: skipped a standup-prep claim entirely\n  · 4 additional traces in the archive.\n\nMachine-only — surfaced for your awareness, not extracted from today's sources.",
    categories: ["preference", "meta"],
    verifiable: false,
  },
  {
    id: 11,
    time: "16:20",
    icon: "briefing",
    source: "Briefing · daily prep",
    text: "Three new engineers start Monday — Lin, Aiden, Tomas. None onboarded to Slack yet.",
    desc: "From HR briefing packet, cross-checked against Slack member list.",
    categories: ["hiring", "onboarding"],
  },
  {
    id: 12,
    time: "17:45",
    icon: "slack",
    source: "Slack · #incidents",
    text: "EU region p95 latency up 31% since Tuesday — likely related to the auth refactor.",
    desc: "Auto-alert from monitoring, manually corroborated by Aiden.",
    detail: "Alert payload:\nregion: eu-west-1\nmetric: api.p95_ms\nbaseline (7d): 142ms\ncurrent (1h): 186ms (+31%)\nfirst breach: 2026-05-21 09:40 UTC\n\nAiden 17:38: \"Pretty sure this is the new session middleware double-hopping. Looking now.\"",
    categories: ["incident", "performance"],
  },
];
